FROM golang:1.23.3 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /url-shortener

# EXPOSE 8080

# CMD [ "/url-shortener" ]

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage  /url-shortener /url-shortener

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/url-shortener"]
